#pragma once

#include <chrono>
#include <compare>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace ibalgotrade {

enum class Side : std::uint8_t { Buy, Sell };
enum class OrderType : std::uint8_t { Market, Limit };

struct Order {
    std::uint64_t id;
    std::string symbol;
    Side side;
    OrderType type;
    double price = 0.0;          // 0 for market orders
    std::int64_t quantity = 0;
    std::chrono::nanoseconds timestamp{};
};

struct Fill {
    std::uint64_t order_id;
    std::uint64_t counter_order_id;
    double price;
    std::int64_t quantity;
};

struct PriceLevel {
    double price;
    std::int64_t total_quantity;
    int order_count;
};

// Price-time priority limit order book for a single symbol.
class LimitOrderBook {
public:
    explicit LimitOrderBook(std::string symbol);

    // Returns fills generated by this order. A market sell crosses
    // against the bid side, a market buy against the ask side.
    [[nodiscard]] std::vector<Fill> add(Order order);
    void cancel(std::uint64_t order_id);

    [[nodiscard]] std::optional<double> best_bid() const;
    [[nodiscard]] std::optional<double> best_ask() const;
    [[nodiscard]] std::int64_t bid_size() const;
    [[nodiscard]] std::int64_t ask_size() const;
    [[nodiscard]] std::vector<PriceLevel> bid_levels() const;
    [[nodiscard]] std::vector<PriceLevel> ask_levels() const;
    [[nodiscard]] const std::string& symbol() const;
    [[nodiscard]] std::size_t order_count() const;

private:
    struct Level {
        double price;
        std::int64_t quantity;
        std::uint64_t order_id;
    };

    std::string symbol_;
    // Bids: ascending price (back = best). Asks: descending (back = best).
    std::vector<Level> bids_;
    std::vector<Level> asks_;
};

}  // namespace ibalgotrade
